import hashlib, json
from pathlib import Path
root=Path(__file__).resolve().parents[4]
src=root/'tasks/evidence/CLOSURE-CONTROLS-2026-10-03/hardware.json'
cards=json.loads(src.read_text(encoding="utf-8"))
# Human assessment is limited to whether an already-read-only observation can reduce an evidenced gap.
notes={
'DEBT-CLOSE-CHECK-VERIFY-FORUM-FINDING-01':('No new host read can satisfy this implementation aggregate; the original selectors remain CNR for missing subject captures.','No additional capture; use the original per-card controls and evidence.','No host prereq; closure depends on per-ID real captures.'),
'DEBT-CLOSE-CHECK-VERIFY-GPU-CLOCK-CAP-AB-01':('Native read-only capability receipt exists; supported-clock output is N/A and current/max are observed, but no policy A/B or rollback is evidenced.','No further clock query resolves A/B; only preserve the existing capability receipt.','Controlled clock-policy A/B, workload, soak and rollback need explicit authorization.'),
'DEBT-CLOSE-CHECK-VERIFY-MEMORY-SAVER-01':('Current telemetry snapshot exists, not a recovery soak or causal memory-pressure event.','No read-only action closes it; existing telemetry dry observation is the baseline.','Approved workload/soak and recovery event required.'),
'DEBT-CLOSE-CHECK-VERIFY-USB-HID-POSTUPDATE-01':('Current observation has no attached HID subject and no post-update failure/recovery sequence.','No additional host-only query; a real keyboard/peripheral and update case are prerequisites.','Peripheral plus authorized update/recovery sequence.'),
'DEBT-CLOSE-CHECK-VERIFY-WIFI-ISOLATION-01':('Current wireless interface is unavailable/down; wired link is present. No isolated endpoint/control or recovery sequence.','No networking probe authorized; preserve current read-only observation.','Approved isolated peer/network test and rollback.'),
'DEBT-HOST-DEPLOYED-DRIFT-01':('Existing comparison records two deployed-file divergences. Read-only reinspection cannot reconcile bytes.','None; the captured drift is already explicit.','Owner authorization to synchronize the two host files.'),
'DEBT-PROCESO-SIN-TECHO-TUMBO-LA-MAQUINA-DOS-VECES':('Card is in tasks/done with recierre evidence; no pending read-only action.','None.','None indicated; already done.'),
'DEBT-TELEMETRY-HISTORICAL-UNDISPOSED-20260908-01':('Recovered metadata exists; three historical events still need explicit disposition/source/evidence.','No system read can supply owner disposition.','Human decision per event.'),
'DELTA-FORUM-APT-ARM64-SOURCE-VALIDATION-01':('Archived canaries include signed metadata, package index hashes and mutation negative. The package-manager source decision remains external and source/target scope is not a host-read question.','No new host query; use archived signed canary and exact external decision binding already in evidence set.','Human/external trust decision and target source scope.'),
'DELTA-FORUM-CLOCK-CAP-TRADEOFF-AND-THERMAL-ZONE-GAP-01':('Existing clock capability and thermal inventory are snapshots; current board is GIGABYTE AI TOP ATOM, not the ASUS target in the gap.','No further generic sensor inventory; target-specific platform/OEM docs and an approved experiment are needed.','Exact target board/firmware and approved A/B.'),
'DELTA-FORUM-CUTLASS-SM121-ISA-GATE-01':('No card evidence. Existing native GB10/driver observation can anchor environment only, not SM121 ISA/build/runtime support.','A read-only version query could record compiler/CUDA/CUTLASS already installed, if present; it cannot prove kernel execution.','Installed toolchain and authorized non-installing build/runtime validation.'),
'DELTA-FORUM-CX7-FW-UPDATE-GUARD-01':('No CX7 subject evidence; no firmware change is allowed.','None useful without CX7 adapter and exact OEM firmware release/candidate.','CX7 hardware, OEM release evidence and separately approved update/rollback.'),
'DELTA-FORUM-CX7-PHYSICAL-TOPOLOGY-ALIAS-CHECK-01':('No CX7 paired topology capture.','If the adapter is attached, one read-only PCI/HCA identity capture can bind BDF/PSID; current evidence does not show the subject.','CX7 hardware and known port/cable map.'),
'DELTA-FORUM-CX7-POSTHOTPLUG-01':('No post-hotplug sequence; hotplug is prohibited in this task.','None under current authorization.','Human-approved hotplug/recovery sequence on CX7.'),
'DELTA-FORUM-CX7-RDMA-ASYMMETRY-RETEST-01':('No paired direction, cold/sequential reboot, or hotplug samples.','Current PCI inventory cannot substitute for per-scenario RDMA transfer records.','CX7 pair, approved reboot/hotplug plan, cable topology and OEM stack.'),
'DELTA-FORUM-DUALSPARK-POWER-RESET-RECOVERY-01':('No repeated A/B power-reset recovery observations.','No read-only action can induce the required recovery case.','DualSpark hardware and approved repeated reset/recovery plan.'),
'DELTA-FORUM-KV-QUANT-METRIC-PROVENANCE-GATE-01':('No model/workload outputs or metric provenance.','No read-only system inventory closes the comparison; preserve exact model/tokenizer/workload artifacts when available.','Authorized inference comparison and trusted reference metrics.'),
'DELTA-FORUM-MEMORY-RECOVERY-SOAK-01':('Dry-run telemetry is a short snapshot; no multi-hour PID-bound workload/client/server termination chronology.','No further one-shot reading adds meaningful coverage.','Predeclared workload, cadence/soak and approved termination/recovery test.'),
'DELTA-FORUM-OTA-DRIVER-KERNEL-EFFECTIVE-TUPLE-01':('Current native GPU read confirms GB10/580.178.04; kernel release is separately observed. This improves the current tuple but says nothing about post-OTA reboot/effective tuple.','Bind the existing native NVIDIA receipt to the card evidence; no new probe needed.','OTA image/candidate and approved reboot/rollback.'),
'DELTA-FORUM-RECOVERY-APT-UPDATE-01':('No recovery update canary. Existing signed APT evidence is a different source-validation case.','None; read-only host checks cannot demonstrate recovery path.','Recovery environment, approved update and rollback.'),
'DELTA-FORUM-THERMAL-AUXILIARY-COOLING-AND-CLOCK-CAP-01':('Thermal inventory exists but has no fan inputs; clock capability receipt has N/A supported clocks. No auxiliary-cooling A/B.','No generic sensor reread; target-specific controller/fan readback would help only with the actual target hardware.','External cooling/hardware and authorized clock/cooling A/B.'),
'DELTA-FORUM-THERMAL-TELEMETRY-COVERAGE-01':('Current native thermal summary records 7 zones, 3 hwmon, 11 temperature inputs, 0 fan inputs; this is a completed observation of coverage, not proof of adequate telemetry.','No repeat inventory; retain summary as actual coverage evidence.','Any claim about fan coverage needs a platform with observable fan inputs or external measurement.'),
'DELTA-FORUM-USB-RAID-LINK-ADMISSION-01':('No USB RAID subject/link capture.','If the enclosure is already attached, read-only USB/SCSI link identity/speed could establish current negotiation; no such target appears in evidence.','USB RAID enclosure, expected identity and link-speed contract.'),
'DELTA-ROOT-BACKUP-MOUNT-BOOT-IDENTITY-01':('No external backup mount or expected boot identity in card evidence.','After the intended backup device is attached, read-only findmnt/lsblk/UUID plus current boot_id could bind the actual mount; no target is presently known.','Known backup device/expected UUID and boot identity.'),
'DELTA-ROOT-DISPLAY-CARVEOUT-OEM-FIX-GATE-01':('No display-carveout OEM fix or recovery evidence.','Current GPU identity does not establish OEM-supported carveout settings.','Exact platform/OEM release and approved configuration/recovery.'),
'DELTA-ROOT-GX10-SOC-EC-CABLE-RECOVERY-CANDIDATE-01':('No GX10/EC/cable subject; current thermal host is a different board.','No useful host query without target GX10 and cable/EC identity.','GX10 hardware, OEM compatibility record, cable and approved recovery plan.'),
'DELTA-ROOT-SUBAMBIENT-COOLING-AND-UMA-CANARY-01':('No subambient/UMA canary. No cooling hardware intervention is authorized.','None; ambient/thermal snapshot cannot validate subambient safety or UMA behavior.','Approved test plan, compatible cooling instrumentation and target hardware.'),
'FEATURE-APT-CRITICAL-METAPACKAGE-GUARD':('Existing APT captures show lock denial and absent aisleriot; no integrated removal-guard execution on the actual package subject.','No additional host probe for absent package; isolated apt-root negative canary belongs to separate guarded harness.','Reproducible isolated package-state fixture, not host package removal.'),
'FEATURE-FORUM-DESKTOP-SESSION-POSTUPDATE-01':('Current graphical target/GDM/seat0 and SSH are observed healthy; no post-update black-screen/recovery/rollback event.','No read-only action can recreate the post-update failure.','Target update and approved session recovery/rollback case.'),
'FEATURE-FORUM-GB10-RUNTIME-COMPAT-01':('Native GB10/driver/CUDA identity and container preflight exist; functional workload result is missing.','No extra version query needed; bind current native NVIDIA receipt. A runtime workload would exceed this read-only assignment.','Approved minimal functional workload and image digest contract.'),
'FEATURE-FORUM-GPU-CLOCK-CAP-AB-01':('Readonly receipt shows current/max clocks, policy service declaration, and N/A supported-clock query. It does not show policy readback, A/B, soak, telemetry association or rollback.','No further query justified; changing clocks/workload is prohibited.','Approved workload-bound A/B, soak and policy rollback.'),
'FEATURE-FORUM-GPU-GSP-BOOT-HEALTH-01':('Current healthy GPU identity is not a GSP boot failure or recovery.','No read-only query reproduces GSP boot failure.','A known GSP incident/candidate and approved boot/recovery test.'),
'FEATURE-FORUM-NVME-READONLY-01':('The test file has no original selector for a real subject check. Existing instrument lab and /tmp-to-/dev/shm regular-file copy are signals-only; OEM/failing-NVMe/device-recovery evidence remains absent.','Development is required: add a real source-generated selector/assertion to tests/test_nvme_readonly.py before treating the existing instrument test as a card gate. For subject evidence, an external trusted digest and read-only comparison can help; no device writes.','Known independent reference data, target NVMe/OEM recovery evidence, and separately authorized device fault/recovery case.'),
'FEATURE-FORUM-PROVIDER-FALLBACK-REGRESSION-01':('Provider trace/preflight artifacts exist, but no real post-respawn request, fallback result or CPU-only negative control.','No read-only inventory can validate request handling.','Approved service request trace and controlled fallback test.'),
'FEATURE-FORUM-RESCUE-RUNBOOK-01':('Current systemd state does not demonstrate rescue.target entry, recovery, or rollback.','No read-only query can establish a rescue transition.','Approved rescue/rollback test window.'),
'FEATURE-FORUM-SBSA-WATCHDOG-STATE-01':('Owner query is unprivileged fuser rc1/empty; sysfs reports active/timeout60/nowayout0 and systemd runtime watchdog 1min. Device owner attribution remains unknown.','A privileged read-only lsof/fuser attribution of /dev/watchdog0 could reduce owner uncertainty; do not repeat the unprivileged query.','Permission for read-only device-owner attribution; OEM recovery policy still required.'),
'FEATURE-FORUM-WIFI-ISOLATION-01':('Current Wi-Fi observation has no active wireless endpoint or isolated peer; the selector is CNR for raw subject commands.','No network probe authorized; no new host query.','Approved isolated AP/peer, endpoint policy and recovery.'),
'FEATURE-USB-HID-POSTUPDATE-CHECK':('No visible HID device in current observation; no keyboard/update/recovery sequence.','No useful host-only query while no HID is attached.','Real HID peripheral and approved update/recovery case.'),
'FORUM-00-CX7-HOTPLUG-FAN-PROTECTION':('Progress evidence records no fan RPM input and no CX7/fan A/B; no blacklist or test is authorized.','No read-only action can prove protection without an observable fan or CX7 load condition.','CX7 hardware, external tachometer/meter and approved hotplug/canary plan.'),
'FORUM-00-DGX-OTA-DRM-COMPAT-PREFLIGHT':('Existing preflight has cmdline data but effective nvidia_drm modeset read was permission-denied/CNR.','One privileged read-only read of /sys/module/nvidia_drm/parameters/modeset would close that specific observation gap; does not close OTA compatibility.','Read permission; OTA target/recovery evidence remains external.'),
'FORUM-00-DOCKER-OOM-RESTART-LOOP':('The current close_check has a false-green gap: ten unit tests pass without a physical containment control. Docker inventory exists, but no OOM/restart/recovery chronology or bounded policy result.','Development is required first: add the real containment assertion to tests/test_workload_restart_containment.py and its source-generated registration; no host OOM experiment is permitted here.','After the test gate is repaired, an explicitly approved controlled OOM/restart test and target service are still required for subject closure.'),
'FORUM-00-GB10-THERMAL-RESIDENCY-ADMISSION':('Two-event dry-run telemetry is a snapshot, not independent-sensor residency/idle/load interval coverage.','No repeat thermal scan; it would duplicate existing coverage.','Approved sustained workload/thermal soak and independent sensor interpretation.'),
'FORUM-00-KERNEL-INITRD-UPDATE-GATE':('Current kernel/driver facts exist; package/module preflight reports missing apt_check/module_ready and APT lock permission denial.','A bounded read-only dpkg-query ownership/version and modinfo path/signature query may resolve current package/module provenance; do not run package operations.','Root/read permissions for provenance; update/reboot A/B and recovery remain separately authorized.'),
'FORUM-00-REALTEK-EEE-DIRECT-LINK':('Current enP7s7 EEE enabled/inactive; partner modes unavailable. No peer, direct-link A/B, stall, mitigation or rollback.','No further local ethtool query adds a peer/direct-link test.','Direct-link peer and approved controlled network A/B.'),
'FORUM-02-GX10-READ-INTEGRITY':('NVMe inventory/read-integrity instrument evidence exists, but no independent known digest, copy comparison, cache-controlled read or GX10 target binding.','No meaningful extra scan without an independent reference dataset.','Known external digest/dataset and GX10 target; read-only validation only.'),
'FORUM-02-USB-UVC-EP0':('USB tree/kernel logs are observed; no UVC device/stream, EP0 sequence, regression/fix or rollback.','No useful query without camera streaming subject.','UVC camera, approved streaming/recovery sequence and supported version matrix.'),
'FORUM-REALTEK-DRIVER-BINDING-01':('Current enP7s7 binds r8127 v11.014.00-NAPI; package ownership/signature, boot A/B, alternate-driver control and rollback absent.','Read-only dpkg-query -S plus modinfo -n/version/signature can improve package provenance if available; avoid repeating current PCI/module version inventory.','Permission for package/module provenance; reboot/A-B and rollback need approval.'),
}
assert len(cards)==47 and len({c['id'] for c in cards})==47
batches=[]
for n in range(1,6):
 p=Path(f'/tmp/bb-hw-readonly-evidence-map/batch-{n:02}.json')
 batches.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
items=[]
for i,c in enumerate(cards,1):
 batch=(i-1)//10+1
 b=json.loads(Path(f'/tmp/bb-hw-readonly-evidence-map/batch-{batch:02}.json').read_text(encoding="utf-8"))
 entry=next(x for x in b['items'] if x['id']==c['id'])
 assert c['id'] in notes, c['id']
 current,action,prereq=notes[c['id']]
 ev=[]
 for e in entry['evidence_files']:
  ev.append({'path':e.get('path'), 'sha256':e.get('sha256'), 'bytes':e.get('bytes')})
 items.append({'source_order':i,'id':c['id'],'card_path':c['path'],'close_check':c['close_check'],'evidence_files':ev,'current_assessment':current,'useful_readonly_action':action,'prerequisite_or_blocker':prereq,'generated_batch':batch})
assert set(x['id'] for x in items)==set(c['id'] for c in cards)
assert all(sum(x['id']==c['id'] for x in items)==1 for c in cards)
source_hash=hashlib.sha256(src.read_bytes()).hexdigest()
out={'source':str(src),'source_sha256':source_hash,'count':len(items),'batch_size_max':10,'batches':batches,'items':items,'limitations':'Evidence map only. No host commands were run. Caller-supplied/archive hashes prove byte consistency, not provenance or OEM authority. CNR/UNKNOWN remains open until raw subject evidence satisfies each original close_check.'}
opath=Path('/tmp/bb-hw-readonly-evidence-map/hardware-readonly-evidence-map.json'); opath.write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n', encoding='utf-8')
print('rows',len(items),'unique',len({x['id'] for x in items}),'source_sha256',source_hash,'map_sha256',hashlib.sha256(opath.read_bytes()).hexdigest())
for x in batches: print(x)
