Dir::Etc "/tmp/bb-apt-source-canary-vc12s6vn/etc";
Dir::Etc::main "/tmp/bb-apt-source-canary-vc12s6vn/etc/empty-main.conf";
Dir::Etc::parts "/tmp/bb-apt-source-canary-vc12s6vn/etc/empty-parts";
Dir::Etc::sourcelist "/tmp/bb-apt-source-canary-vc12s6vn/etc/sources.list";
Dir::Etc::sourceparts "/tmp/bb-apt-source-canary-vc12s6vn/etc/sources.list.d";
Dir::State "/tmp/bb-apt-source-canary-vc12s6vn/state";
Dir::State::lists "/tmp/bb-apt-source-canary-vc12s6vn/state/lists";
Dir::State::status "/var/lib/dpkg/status";
Dir::Cache "/tmp/bb-apt-source-canary-vc12s6vn/cache";
Dir::Cache::archives "/tmp/bb-apt-source-canary-vc12s6vn/cache/archives";
Dir::Cache::pkgcache "/tmp/bb-apt-source-canary-vc12s6vn/cache/pkgcache.bin";
Dir::Cache::srcpkgcache "/tmp/bb-apt-source-canary-vc12s6vn/cache/srcpkgcache.bin";
Dir::Log "/tmp/bb-apt-source-canary-vc12s6vn/log";
APT::Architecture "arm64";
APT::Architectures:: "arm64";
Acquire::Languages "none";
Acquire::Retries "0";
Acquire::http::Timeout "10";
Acquire::https::Timeout "10";
APT::Update::Error-Mode "any";
