Dir::Etc "/tmp/bb-apt-healthy-canary-66_4unu2/etc";
Dir::Etc::main "/tmp/bb-apt-healthy-canary-66_4unu2/etc/empty-main.conf";
Dir::Etc::parts "/tmp/bb-apt-healthy-canary-66_4unu2/etc/empty-parts";
Dir::Etc::sourcelist "/tmp/bb-apt-healthy-canary-66_4unu2/etc/sources.list";
Dir::Etc::sourceparts "/tmp/bb-apt-healthy-canary-66_4unu2/etc/sources.list.d";
Dir::State "/tmp/bb-apt-healthy-canary-66_4unu2/state";
Dir::State::lists "/tmp/bb-apt-healthy-canary-66_4unu2/state/lists";
Dir::State::status "/var/lib/dpkg/status";
Dir::Cache "/tmp/bb-apt-healthy-canary-66_4unu2/cache";
Dir::Cache::archives "/tmp/bb-apt-healthy-canary-66_4unu2/cache/archives";
Dir::Cache::pkgcache "/tmp/bb-apt-healthy-canary-66_4unu2/cache/pkgcache.bin";
Dir::Cache::srcpkgcache "/tmp/bb-apt-healthy-canary-66_4unu2/cache/srcpkgcache.bin";
Dir::Log "/tmp/bb-apt-healthy-canary-66_4unu2/log";
APT::Architecture "arm64";
APT::Architectures:: "arm64";
Acquire::Languages "none";
Acquire::Retries "0";
Acquire::http::Timeout "10";
Acquire::https::Timeout "10";
APT::Update::Error-Mode "any";
Acquire::IndexTargets::deb::DEP-11::DefaultEnabled "false";
